export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const SHOW_PRELOADER = "SHOW_PRELOADER"
export const SHOW_PRELOADER_COMPLETE = "SHOW_PRELOADER_COMPLETE";
export const BALANCE_SUCCESS = "BALANCE_SUCCESS";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS";
export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";